from __future__ import annotations

from typing import Protocol, runtime_checkable

from vertical_brain.core.models import Chunk, Link, Node


@runtime_checkable
class StorageProvider(Protocol):
    """Interface implemented by both JsonStore and SQLiteStore.

    Note: ``search()``, ``gold_summary_path()`` and ``transaction()`` are
    intentionally excluded because they are not universally implemented by
    both backends. ``log_audit()`` is optional and discovered via ``hasattr``.
    """

    def ensure_node(self, path: str) -> Node: ...

    def save_chunk(self, chunk: Chunk) -> Chunk: ...

    def save_link(self, link: Link) -> Link: ...

    def update_chunk(self, chunk: Chunk) -> Chunk: ...

    def get_node(self, path: str) -> Node | None: ...

    def list_nodes(self) -> list[Node]: ...

    def list_chunks(self) -> list[Chunk]: ...

    def list_links(self) -> list[Link]: ...

    def get_link(self, link_id: str) -> Link | None: ...

    def get_peer_links(self, path: str) -> list[Link]: ...

    def get_peer_paths(self, path: str) -> list[str]: ...

    def get_chunks_by_path(self, path: str) -> list[Chunk]: ...

    def get_ancestors(self, path: str) -> list[str]: ...

    def tree_text(self) -> str: ...
