from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Any, Dict, List, Optional, Protocol, runtime_checkable

from vertical_brain.core.models import Chunk, Link, Node, SearchResult


@runtime_checkable
class StorageProvider(Protocol):
    """Core interface implemented by both JsonStore and SQLiteStore."""

    def ensure_node(self, path: str) -> Node: ...
    def save_chunk(self, chunk: Chunk) -> Chunk: ...
    def save_link(self, link: Link) -> Link: ...
    def update_chunk(self, chunk: Chunk) -> Chunk: ...
    def update_node(self, node: Node) -> Node: ...
    def get_node(self, path: str) -> Optional[Node]: ...
    def list_nodes(self) -> List[Node]: ...
    def list_chunks(self) -> List[Chunk]: ...
    def list_links(self) -> List[Link]: ...
    def get_link(self, link_id: str) -> Optional[Link]: ...
    def get_peer_links(self, path: str) -> List[Link]: ...
    def get_peer_paths(self, path: str) -> List[str]: ...
    def get_chunks_by_path(self, path: str, include_children: bool = False) -> List[Chunk]: ...
    def get_ancestors(self, path: str) -> List[str]: ...
    def tree_text(self) -> str: ...


@runtime_checkable
class EmbeddingSchemaStorageProvider(Protocol):
    """Optional extension for backends that persist embedding model schema."""

    def get_embedding_schema(self) -> Optional[Dict[str, Any]]: ...
    def set_embedding_schema(self, model_name: str, vector_dimension: int) -> None: ...


@runtime_checkable
class RenameCapableStorageProvider(Protocol):
    """Optional extension for backends that support atomic namespace rename."""

    def rename_namespace(self, old_prefix: str, new_prefix: str) -> None: ...


@runtime_checkable
class SearchableStorageProvider(Protocol):
    """Optional extension for backends with native full-text search support."""

    def search(
        self,
        query: str,
        *,
        root_path: Optional[str] = None,
        limit: int = 10,
        include_stale: bool = False,
    ) -> List[SearchResult]: ...


@runtime_checkable
class TransactionalStorageProvider(Protocol):
    """Optional extension for backends that support atomic transactions."""

    def transaction(self) -> AbstractContextManager[None]: ...


@runtime_checkable
class AuditableStorageProvider(Protocol):
    """Optional extension for backends that persist an operation audit log."""

    def log_audit(self, operation: Any, result: Any) -> None: ...
    def list_audit(self) -> List[Dict[str, Any]]: ...


@runtime_checkable
class VectorCacheStorageProvider(Protocol):
    """Optional extension for backends that persist embedding vectors across restarts."""

    def get_vector(self, content_hash: str, model_name: str) -> Optional[List[float]]: ...
    def set_vector(self, content_hash: str, model_name: str, vector: List[float]) -> None: ...
    def delete_vectors_for_model(self, model_name: str) -> int: ...
